// <auto-generated />
using System;
using GeradorDeProtocolo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeradorDeProtocolo.Migrations
{
    [DbContext(typeof(ProtocoloContext))]
    partial class ProtocoloContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeradorDeProtocolo.Models.Assunto", b =>
                {
                    b.Property<int>("AssuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssuntoDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupoAssuntoId")
                        .HasColumnType("int");

                    b.HasKey("AssuntoId");

                    b.HasIndex("GrupoAssuntoId");

                    b.ToTable("Assuntos");
                });

            modelBuilder.Entity("GeradorDeProtocolo.Models.GrupoAssunto", b =>
                {
                    b.Property<int>("GrupoAssuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrupoAssuntoId");

                    b.ToTable("GrupoAssuntos");
                });

            modelBuilder.Entity("GeradorDeProtocolo.Models.Local", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GrupoAssuntoId")
                        .HasColumnType("int");

                    b.Property<bool?>("LocalAbertura")
                        .HasColumnType("bit");

                    b.Property<bool?>("LocalArquivamento")
                        .HasColumnType("bit");

                    b.Property<string>("LocalDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalDiasPermanencia")
                        .HasColumnType("int");

                    b.HasKey("LocalId");

                    b.HasIndex("GrupoAssuntoId");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("GeradorDeProtocolo.Models.OrigemDeAbertura", b =>
                {
                    b.Property<int>("OrigemDeAberturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrigemDeAberturaId");

                    b.ToTable("OrigemDeAberturas");
                });

            modelBuilder.Entity("GeradorDeProtocolo.Models.Sublocal", b =>
                {
                    b.Property<int>("SublocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LocalId")
                        .HasColumnType("int");

                    b.Property<string>("SublocalDescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SublocalDiasPermanecia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SublocalId");

                    b.HasIndex("LocalId");

                    b.ToTable("sublocais");
                });

            modelBuilder.Entity("GeradorDeProtocolo.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("GeradorDeProtocolo.Models.Assunto", b =>
                {
                    b.HasOne("GeradorDeProtocolo.Models.GrupoAssunto", "GrupoAssunto")
                        .WithMany("Assuntos")
                        .HasForeignKey("GrupoAssuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeradorDeProtocolo.Models.Local", b =>
                {
                    b.HasOne("GeradorDeProtocolo.Models.GrupoAssunto", "GrupoAssunto")
                        .WithMany()
                        .HasForeignKey("GrupoAssuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeradorDeProtocolo.Models.Sublocal", b =>
                {
                    b.HasOne("GeradorDeProtocolo.Models.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
